apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: YOUR_DOCKERHUB_USER/demo-app:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: APP_VERSION
          value: "v1"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-svc
spec:
  type: NodePort
  selector:
    app: demo-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
